const surahs = [
    { Order: "001", verses: "007", name: "الفاتحة", type: "مكية", summary: "أم الكتاب، تتضمن الثناء على الله، طلب الهداية، والدعاء بالثبات على الصراط المستقيم." },
    { Order: "002", verses: "286", name: "البقرة", type: "مدنية", summary: "أطول سورة، تعالج أحكام الشريعة، القصص، الإيمان، التعاملات، والاختبار بالإيمان والعمل." },
    { Order: "003", verses: "200", name: "آل عمران", type: "مدنية", summary: "تؤكد أهمية الثبات في الإيمان، الدعوة، وحدة الأمة، وأحداث غزوة أحد." },
    { Order: "004", verses: "176", name: "النساء", type: "مدنية", summary: "تعالج قضايا الأسرة، الميراث، العدل، وحماية الحقوق." },
    { Order: "005", verses: "120", name: "المائدة", type: "مدنية", summary: "تتحدث عن العهود والمواثيق، الحلال والحرام، وأخلاقيات المعاملات." },
    { Order: "006", verses: "165", name: "الأنعام", type: "مكية", summary: "تركز على التوحيد، الدلائل الكونية، والرد على الشرك." },
    { Order: "007", verses: "206", name: "الأعراف", type: "مكية", summary: "قصص الأمم السابقة، الدعوة للإصلاح، وعواقب التكذيب." },
    { Order: "008", verses: "075", name: "الأنفال", type: "مدنية", summary: "تناقش الغنائم وأخلاقيات القتال." },
    { Order: "009", verses: "129", name: "التوبة", type: "مدنية", summary: "تُعنى بالمنافقين، الجهاد، والتحذير من الخيانة." },
    { Order: "010", verses: "109", name: "يونس", type: "مكية", summary: "دعوة للتوحيد، قصص الأنبياء، ووعد الله للمؤمنين." },
    { Order: "011", verses: "123", name: "هود", type: "مكية", summary: "تثبيت النبي بقصص الأنبياء السابقين." },
    { Order: "012", verses: "111", name: "يوسف", type: "مكية", summary: "قصة النبي يوسف عبرةً في الصبر والتوكل على الله." },
    { Order: "013", verses: "043", name: "الرعد", type: "مدنية", summary: "دلائل قدرة الله وتوحيده." },
    { Order: "014", verses: "052", name: "إبراهيم", type: "مكية", summary: "شكر النعم والتحذير من الكفر." },
    { Order: "015", verses: "099", name: "الحجر", type: "مكية", summary: "وعد الله بالحفظ، وتحذير المكذبين." },
    { Order: "016", verses: "128", name: "النحل", type: "مكية", summary: "نعم الله، توحيده، وتثبيت النبي." },
    { Order: "017", verses: "111", name: "الإسراء", type: "مكية", summary: "الإسراء والمعراج، الأخلاقيات، وأحكام فردية." },
    { Order: "018", verses: "110", name: "الكهف", type: "مكية", summary: "قصص الفتية، الكنز، موسى والخضر، وذي القرنين." },
    { Order: "019", verses: "098", name: "مريم", type: "مكية", summary: "قصة مريم، عيسى، وزكريا." },
    { Order: "020", verses: "135", name: "طه", type: "مكية", summary: "قصة موسى وفرعون، وأهمية القرآن." },
    { Order: "021", verses: "112", name: "الأنبياء", type: "مكية", summary: "قصص الأنبياء، الحساب، وعظمة الخالق." },
    { Order: "022", verses: "078", name: "الحج", type: "مدنية", summary: "عبودية الله وأحكام الحج." },
    { Order: "023", verses: "118", name: "المؤمنون", type: "مكية", summary: "صفات المؤمنين، الخلق، والحساب." },
    { Order: "024", verses: "064", name: "النور", type: "مدنية", summary: "أحكام اجتماعية وآداب الاستئذان." },
    { Order: "025", verses: "077", name: "الفرقان", type: "مكية", summary: "الفرق بين المؤمنين والكافرين." },
    { Order: "026", verses: "227", name: "الشعراء", type: "مكية", summary: "قصص الأنبياء والدعوة." },
    { Order: "027", verses: "093", name: "النمل", type: "مكية", summary: "قصة سليمان، وملكة سبأ." },
    { Order: "028", verses: "088", name: "القصص", type: "مكية", summary: "قصة موسى وفرعون." },
    { Order: "029", verses: "069", name: "العنكبوت", type: "مكية", summary: "الابتلاءات وثبات المؤمنين." },
    { Order: "030", verses: "060", name: "الروم", type: "مكية", summary: "أحداث تاريخية ودلائل الإيمان." },
    { Order: "031", verses: "034", name: "لقمان", type: "مكية", summary: "الحكمة والنصائح للأبناء." },
    { Order: "032", verses: "030", name: "السجدة", type: "مكية", summary: "دلائل البعث وتوحيد الله." },
    { Order: "033", verses: "073", name: "الأحزاب", type: "مدنية", summary: "غزوة الأحزاب وأحكام اجتماعية." },
    { Order: "034", verses: "054", name: "سبأ", type: "مكية", summary: "النعم وشكرها." },
    { Order: "035", verses: "045", name: "فاطر", type: "مكية", summary: "عظمة خلق الله." },
    { Order: "036", verses: "083", name: "يس", type: "مكية", summary: "دلائل القدرة الإلهية." },
    { Order: "037", verses: "182", name: "الصافات", type: "مكية", summary: "توحيد الله وقصص الأنبياء." },
    { Order: "038", verses: "088", name: "ص", type: "مكية", summary: "دعوة للتوحيد وعاقبة المكذبين." },
    { Order: "039", verses: "075", name: "الزمر", type: "مكية", summary: "الإخلاص في العبادة." },
    { Order: "040", verses: "085", name: "غافر", type: "مكية", summary: "العاقبة للمتقين." },
    { Order: "041", verses: "054", name: "فصلت", type: "مكية", summary: "دلائل الوحي والتوحيد." },
    { Order: "042", verses: "053", name: "الشورى", type: "مكية", summary: "أهمية الشورى." },
    { Order: "043", verses: "089", name: "الزخرف", type: "مكية", summary: "الحياة الدنيا وزخرفها." },
    { Order: "044", verses: "059", name: "الدخان", type: "مكية", summary: "التحذير من يوم القيامة." },
    { Order: "045", verses: "037", name: "الجاثية", type: "مكية", summary: "عاقبة المكذبين." },
    { Order: "046", verses: "035", name: "الأحقاف", type: "مكية", summary: "قصص عاد وثمود." },
    { Order: "047", verses: "038", name: "محمد", type: "مدنية", summary: "الجهاد وأخلاق المسلمين." },
    { Order: "048", verses: "029", name: "الفتح", type: "مدنية", summary: "صلح الحديبية." },
    { Order: "049", verses: "018", name: "الحجرات", type: "مدنية", summary: "آداب المجتمع." },
    { Order: "050", verses: "045", name: "ق", type: "مكية", summary: "البعث والحساب." },
    { Order: "051", verses: "060", name: "الذاريات", type: "مكية", summary: "عاقبة المتقين." },
    { Order: "052", verses: "049", name: "الطور", type: "مكية", summary: "دلائل التوحيد." },
    { Order: "053", verses: "062", name: "النجم", type: "مكية", summary: "معجزة المعراج." },
    { Order: "054", verses: "055", name: "القمر", type: "مكية", summary: "أحداث يوم القيامة." },
    { Order: "055", verses: "078", name: "الرحمن", type: "مدنية", summary: "نعم الله المتكررة." },
    { Order: "056", verses: "096", name: "الواقعة", type: "مكية", summary: "أهوال يوم القيامة." },
    { Order: "057", verses: "029", name: "الحديد", type: "مدنية", summary: "الإنفاق في سبيل الله." },
    { Order: "058", verses: "022", name: "المجادلة", type: "مدنية", summary: "أحكام اجتماعية." },
    { Order: "059", verses: "024", name: "الحشر", type: "مدنية", summary: "تطهير المجتمع." },
    { Order: "060", verses: "013", name: "الممتحنة", type: "مدنية", summary: "العلاقات مع غير المسلمين." },
    { Order: "061", verses: "014", name: "الصف", type: "مدنية", summary: "الجهاد والوحدة." },
    { Order: "062", verses: "011", name: "الجمعة", type: "مدنية", summary: "أهمية صلاة الجمعة." },
    { Order: "063", verses: "011", name: "المنافقون", type: "مدنية", summary: "أخلاق المنافقين." },
    { Order: "064", verses: "018", name: "التغابن", type: "مدنية", summary: "الإيمان بالله واليوم الآخر." },
    { Order: "065", verses: "012", name: "الطلاق", type: "مدنية", summary: "أحكام الطلاق." },
    { Order: "066", verses: "012", name: "التحريم", type: "مدنية", summary: "أخلاقيات الأسرة." },
    { Order: "067", verses: "030", name: "الملك", type: "مكية", summary: "ملك الله وقدرته." },
    { Order: "068", verses: "052", name: "القلم", type: "مكية", summary: "الأخلاق والآداب." },
    { Order: "069", verses: "052", name: "الحاقة", type: "مكية", summary: "أهوال يوم القيامة." },
    { Order: "070", verses: "044", name: "المعارج", type: "مكية", summary: "عاقبة المكذبين." },
    { Order: "071", verses: "028", name: "نوح", type: "مكية", summary: "قصة النبي نوح ودعوته." },
    { Order: "072", verses: "028", name: "الجن", type: "مكية", summary: "إيمان الجن بالقرآن." },
    { Order: "073", verses: "020", name: "المزمل", type: "مكية", summary: "أوامر للنبي في العبادة." },
    { Order: "074", verses: "056", name: "المدثر", type: "مكية", summary: "الدعوة والإعداد لها." },
    { Order: "075", verses: "040", name: "القيامة", type: "مكية", summary: "البعث والحساب." },
    { Order: "076", verses: "031", name: "الإنسان", type: "مدنية", summary: "جزاء المتقين." },
    { Order: "077", verses: "050", name: "المرسلات", type: "مكية", summary: "إنذار يوم القيامة." },
    { Order: "078", verses: "040", name: "النبأ", type: "مكية", summary: "أهوال يوم القيامة." },
    { Order: "079", verses: "046", name: "النازعات", type: "مكية", summary: "دلائل البعث." },
    { Order: "080", verses: "042", name: "عبس", type: "مكية", summary: "إهمال النبي للأعمى." },
    { Order: "081", verses: "029", name: "التكوير", type: "مكية", summary: "أهوال القيامة." },
    { Order: "082", verses: "019", name: "الإنفطار", type: "مكية", summary: "دلائل يوم الحساب." },
    { Order: "083", verses: "036", name: "المطففين", type: "مكية", summary: "التحذير من الغش." },
    { Order: "084", verses: "025", name: "الإنشقاق", type: "مكية", summary: "دلائل الآخرة." },
    { Order: "085", verses: "022", name: "البروج", type: "مكية", summary: "التحذير من عاقبة الظلم." },
    { Order: "086", verses: "017", name: "الطارق", type: "مكية", summary: "دلائل قدرة الله." },
    { Order: "087", verses: "019", name: "الأعلى", type: "مكية", summary: "الحث على التذكر والتسبيح." },
    { Order: "088", verses: "026", name: "الغاشية", type: "مكية", summary: "الحساب." },
    { Order: "089", verses: "030", name: "الفجر", type: "مكية", summary: "عاقبة الطغاة." },
    { Order: "090", verses: "020", name: "البلد", type: "مكية", summary: "التحديات في الحياة." },
    { Order: "091", verses: "015", name: "الشمس", type: "مكية", summary: "أهمية تزكية النفس." },
    { Order: "092", verses: "021", name: "الليل", type: "مكية", summary: "العمل في الدنيا." },
    { Order: "093", verses: "011", name: "الضحى", type: "مكية", summary: "فضل الله على النبي." },
    { Order: "094", verses: "008", name: "الشرح", type: "مكية", summary: "تخفيف العبء عن النبي." },
    { Order: "095", verses: "008", name: "التين", type: "مكية", summary: "خلق الإنسان في أحسن تقويم." },
    { Order: "096", verses: "019", name: "العلق", type: "مكية", summary: "بداية الوحي." },
    { Order: "097", verses: "005", name: "القدر", type: "مكية", summary: "ليلة القدر." },
    { Order: "098", verses: "008", name: "البينة", type: "مدنية", summary: "الفرق بين الحق والباطل." },
    { Order: "099", verses: "008", name: "الزلزلة", type: "مدنية", summary: "أحداث يوم القيامة." },
    { Order: "100", verses: "011", name: "العاديات", type: "مكية", summary: "صفة الخيل في الجهاد." },
    { Order: "101", verses: "011", name: "القارعة", type: "مكية", summary: "أهوال يوم القيامة." },
    { Order: "102", verses: "008", name: "التكاثر", type: "مكية", summary: "التحذير من حب المال." },
    { Order: "103", verses: "003", name: "العصر", type: "مكية", summary: "أهمية الوقت." },
    { Order: "104", verses: "009", name: "الهمزة", type: "مكية", summary: "عاقبة السخرية." },
    { Order: "105", verses: "005", name: "الفيل", type: "مكية", summary: "حادثة الفيل." },
    { Order: "106", verses: "004", name: "قريش", type: "مكية", summary: "فضل قريش." },
    { Order: "107", verses: "007", name: "الماعون", type: "مكية", summary: "أفعال المنافقين." },
    { Order: "108", verses: "003", name: "الكوثر", type: "مكية", summary: "نعمة الكوثر." },
    { Order: "109", verses: "006", name: "الكافرون", type: "مكية", summary: "البراءة من الشرك." },
    { Order: "110", verses: "003", name: "النصر", type: "مدنية", summary: "وعد النصر." },
    { Order: "111", verses: "005", name: "المسد", type: "مكية", summary: "مصير أبي لهب." },
    { Order: "112", verses: "004", name: "الإخلاص", type: "مكية", summary: "توحيد الله." },
    { Order: "113", verses: "005", name: "الفلق", type: "مكية", summary: "الاستعاذة." },
    { Order: "114", verses: "006", name: "الناس", type: "مكية", summary: "الاستعاذة من الوسواس." }
];

for (var i = 0; i < surahs.length; i++) {
    var SurahsFilePath;
    SurahsFilePath = [surahs[i] = `quran/${surahs[i].name}.html`]
}